WIP: Lesson5
ozoncp/ocp-tenant-api pull request #2
Opened 2021-06-08 15:33 UTC by uhby07

2021-06-08 17:17 UTC, xmikasax requested changes

2021-06-08 17:17 UTC, xmikasax commented on internal/saver/saver.go
> +		case Last:
Странная политика убирать последний элемент, обычно убирают первый. Но это можно оставить, не так важно.

2021-06-08 17:17 UTC, xmikasax commented on internal/saver/saver.go
> +	s.toClose <- struct{}{}
Здесь надо дождаться завершения горутины work, иначе она может не успеть сделать flush

2021-06-08 18:06 UTC, uhby07 commented on internal/saver/saver.go
> +	s.toClose <- struct{}{}
Исправлено

2021-06-08 18:06 UTC, uhby07 commented on internal/saver/saver.go
> +		case Last:
Добавил ещё одну политику.

2021-06-09 13:25 UTC, xmikasax approved these changes

2021-06-10 18:12 UTC, merged